### ISSUE TITLE
No need for Halogen

### ISSUE THREAD

**Issue by nsaunders** [deemp/purescript-halogen-css-frameworks#2]
I think you can actually drop the `halogen` dependency given that `ClassName` is merely a re-export [from web-html](https://pursuit.purescript.org/packages/purescript-web-html/4.1.0/docs/Web.HTML.Common#t:ClassName). Aside from reducing dependency weight, it will make this library more useful to those who might be using other frameworks.

**Comment by deemp** [comment]
@nsaunders, thank you for an idea! Now, this package doesn't depend on `Halogen`.
